@host = localhost:6969

###
@mac = AA:BB:CC:DD:EE:04
GET http://{{host}}/devices/{{mac}}

###
POST http://{{host}}/devices
Content-Type: application/json

{
    "ip": "192.168.1.111",
    "name": "Fancy Thinkpad",
    "type": "Workstation",
    "mac": "AA:BB:CC:DD:EE:10",
    "locationName": "Headquarters",
    "routerMac": "AA:BB:CC:DD:EE:01",
    "connectionType": "Wifi", 
    "bandwidthMbps": 100,  
    "latencyMs": 30,     
    "packetLoss": "3%"  
}

###
POST http://{{host}}/locations
Content-Type: application/json

{
    "name": "Fancy New Location Name",
    "address": "Little Saint James 2"
}

###
@email = alice@whitehouse.gov
GET http://{{host}}/users/{{email}}/devices

###
@locationName = Headquarters
GET http://{{host}}/locations/{{locationName}}/devices

###
@device = AA:BB:CC:DD:EE:04
GET http://{{host}}/hops/{{device}}

###
@start = AA:BB:CC:DD:EE:09
@end = AA:BB:CC:DD:EE:06
GET http://{{host}}/dijkstra/{{start}}/{{end}}

###
@location = Headquarters
GET http://{{host}}/locations/{{location}}/count
